### ISSUE TITLE
Password support 

### ISSUE THREAD

**Issue by silentshotghost** [hellobloom/core#48]
Why not add password support it’s totally possible as ik you guys are using the https://haveibeenpwned.com/ website

**Comment by djvs** [comment]
Hi silentshotghost - password support in what sense?

**Comment by silentshotghost** [comment]
You enter a password and it scans the database

**Comment by djvs** [comment]
It's outside the scope of this repository, which is used to store Bloom's smart contracts, but we'll certainly consider your request.
